name: sample_2pop
setup_name: minimal
start_date: 2020-02-01
end_date: 2020-08-31
nslots: 1

subpop_setup:
  geodata: model_input/geodata_sample_2pop.csv
  mobility: model_input/mobility_sample_2pop.csv

initial_conditions:
  method: SetInitialConditions
  initial_conditions_file: model_input/ic_2pop.csv
  allow_missing_subpops: TRUE
  allow_missing_compartments: TRUE

compartments:
  infection_stage: ["S", "E", "I", "R"]

seir:
  integration:
    method: rk4
    dt: 1
  parameters:
    sigma:
      value: 1 / 4
    gamma:
      value: 1 / 5
    Ro:
      value: 2.5
  transitions:
    - source: ["S"]
      destination: ["E"]
      rate: ["Ro * gamma"]
      proportional_to: [["S"],["I"]]
      proportion_exponent: ["1","1"]
    - source: ["E"]
      destination: ["I"]
      rate: ["sigma"]
      proportional_to: ["E"]
      proportion_exponent: ["1"]
    - source: ["I"]
      destination: ["R"]
      rate: ["gamma"]
      proportional_to: ["I"]
      proportion_exponent: ["1"]

seir_modifiers:
  scenarios:
    - Ro_all
  modifiers:
    Ro_mod: # assume same for all subpopulations, as a method to fit baseline R0
      method: SinglePeriodModifier
      parameter: Ro
      period_start_date: 2020-02-01
      period_end_date: 2020-08-31
      subpop: "all"
      subpop_groups: "all"
      value: 
        distribution: truncnorm
        mean: 1.0
        sd: 0.001
        a: 0
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: 0.025
        a: -0.1
        b: 0.1
    Ro_lockdown: # allow to vary by subpopulation
      method: SinglePeriodModifier
      parameter: Ro
      period_start_date: 2020-03-15
      period_end_date: 2020-05-01
      subpop: "all"
      value: 
        distribution: truncnorm
        mean: 0.5
        sd: 0.001
        a: 0
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: 0.025
        a: -0.1
        b: 0.1
    Ro_relax: # allow to vary by subpopulation
      method: SinglePeriodModifier
      parameter: Ro
      period_start_date: 2020-05-01
      period_end_date: 2020-07-01
      subpop: "all"
      value: 
        distribution: truncnorm
        mean: 0.8
        sd: 0.001
        a: 0
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: 0.025
        a: -0.1
        b: 0.1
    Ro_all:
      method: StackedModifier
      modifiers: ["Ro_mod","Ro_lockdown","Ro_relax"]


outcomes:
  method: delayframe
  outcomes:
    incidCase: #incidence of detected cases
      source:
        incidence:
          infection_stage: "I"
      probability:
        value: 0.5
      delay:
        value: 5
    incidHosp: #incidence of hospitalizations
      source:
        incidence:
          infection_stage: "I"
      probability:
        value: 0.05
      delay:
        value: 7
      duration:
        value: 10
        name: currHosp # will track number of current hospitalizations (ie prevalence)
    incidDeath: #incidence of deaths
      source: incidHosp
      probability:
        value: 0.2
      delay:
        value: 14

outcome_modifiers:
  scenarios:
    - test_limits
  modifiers:
    # assume that due to limitations in testing, initially the case detection probability was lower
    test_limits:
      method: SinglePeriodModifier
      parameter: incidCase
      subpop: "all"
      period_start_date: 2020-02-01
      period_end_date: 2020-06-01
      value: 
        distribution: truncnorm
        mean: 0.5
        sd: 0.001
        a: 0
        b: 1
      perturbation:
        distribution: truncnorm
        mean: 0
        sd: 0.025
        a: -0.1
        b: 0.1

inference:
  iterations_per_slot: 1
  do_inference: TRUE
  gt_data_path: data/sample_2pop_cases.csv 
  statistics:
    sum_hosp:
      name: "Weekly incident hospitalizations"
      aggregator: sum
      period: "1 weeks"
      #gt_start_date:
      #gt_end_date: 
      sim_var: incidHosp
      data_var: incidH
      remove_na: TRUE
      add_one: TRUE
      likelihood: 
        dist: norm_cov
        param: 0.3
