
seeding:
  method: FromFile
  seeding_file: model_input/seeding_2pop.csv

modifiers:
  scenarios:
    - None
  settings:
    None:
      template: Reduce
      parameter: r0
      period_start_date: 2020-04-01
      period_end_date: 2020-05-15
      value:
        distribution: fixed
        value: 0

