.TH "FLEPIMOP" "1" "2025-04-25" "2.1" "flepimop Manual"
.SH NAME
flepimop \- Flexible Epidemic Modeling Platform...
.SH SYNOPSIS
.B flepimop
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Flexible Epidemic Modeling Platform (FlepiMoP) Command Line Interface
.SH COMMANDS
.PP
\fBmodifiers\fP
  .PP
  See \fBflepimop-modifiers(1)\fP for full documentation on the \fBmodifiers\fP command.
.PP
\fBcompartments\fP
  Add commands for working with FlepiMoP...
  See \fBflepimop-compartments(1)\fP for full documentation on the \fBcompartments\fP command.
.PP
\fBbatch-calibrate\fP
  Submit a calibration job to a batch system.
  See \fBflepimop-batch-calibrate(1)\fP for full documentation on the \fBbatch-calibrate\fP command.
.PP
\fBsimulate\fP
  Forward simulate a model using gempyor.
  See \fBflepimop-simulate(1)\fP for full documentation on the \fBsimulate\fP command.
.PP
\fBsync\fP
  Sync flepimop files between local and...
  See \fBflepimop-sync(1)\fP for full documentation on the \fBsync\fP command.
.PP
\fBpatch\fP
  Merge configuration files.
  See \fBflepimop-patch(1)\fP for full documentation on the \fBpatch\fP command.
