.TH "FLEPIMOP COMPARTMENTS" "1" "2025-06-25" "1" "flepimop compartments Manual"
.SH NAME
flepimop\-compartments \- Add commands for working with FlepiMoP...
.SH SYNOPSIS
.B flepimop compartments
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Add commands for working with FlepiMoP compartments.
    
.SH COMMANDS
.PP
\fBplot\fP
  Command to generate a plot representing...
  See \fBflepimop compartments-plot(1)\fP for full documentation on the \fBplot\fP command.
.PP
\fBexport\fP
  Export compartment information to a CSV file.
  See \fBflepimop compartments-export(1)\fP for full documentation on the \fBexport\fP command.
