.TH "FLEPIMOP MODIFIERS" "1" "2025-04-30" "1" "flepimop modifiers Manual"
.SH NAME
flepimop\-modifiers \- 
.SH SYNOPSIS
.B flepimop modifiers
[OPTIONS] COMMAND [ARGS]...
.SH COMMANDS
.PP
\fBconfig-plot\fP
  Plot the seir/outcome modifiers affects on...
  See \fBflepimop modifiers-config-plot(1)\fP for full documentation on the \fBconfig-plot\fP command.
