name: Bug Report
description: File a bug report
title: "[Bug]: "

body:

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug/issue
      placeholder: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      placeholder: Run code '...' and expect this error '...'
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment, if relevant
      placeholder: OS (e.g. Ubuntu 22.04, macOS 14.5, etc.). R and/or Python version (terminal command `R --version` or `python --version`). fleiMoP branch and/or commit if relevant (`git rev-parse HEAD`)
    validations:
      required: false
