name: sample_2pop
setup_name: minimal
start_date: 2020-02-01
end_date: 2020-08-31
data_path: model_input
nslots: 1

subpop_setup:
  geodata: model_input/geodata_sample_2pop.csv
  mobility: model_input/mobility_sample_2pop.csv

initial_conditions:
  method: SetInitialConditions
  initial_conditions_file: model_input/ic_2pop.csv
  allow_missing_subpops: TRUE
  allow_missing_compartments: TRUE

compartments:
  infection_stage: ["S", "E", "I", "R"]

seir:
  integration:
    method: rk4
    dt: 1
  parameters:
    sigma:
      value: 1 / 4
    gamma:
      value: 1 / 5
    Ro:
      value: 2.5
  transitions:
    - source: ["S"]
      destination: ["E"]
      rate: ["Ro * gamma"]
      proportional_to: [["S"],["I"]]
      proportion_exponent: ["1","1"]
    - source: ["E"]
      destination: ["I"]
      rate: ["sigma"]
      proportional_to: ["E"]
      proportion_exponent: ["1"]
    - source: ["I"]
      destination: ["R"]
      rate: ["gamma"]
      proportional_to: ["I"]
      proportion_exponent: ["1"]

seir_modifiers:
  scenarios:
    - Ro_lockdown
    - Ro_all
  modifiers:
    Ro_lockdown:
      method: SinglePeriodModifier
      parameter: Ro
      period_start_date: 2020-03-15
      period_end_date: 2020-05-01
      subpop: "all"
      value: 0.8
    Ro_relax:
      method: SinglePeriodModifier
      parameter: Ro
      period_start_date: 2020-05-01
      period_end_date: 2020-07-01
      subpop: "all"
      value: 0.4
    Ro_all:
      method: StackedModifier
      modifiers: ["Ro_lockdown","Ro_relax"]


outcomes:
  method: delayframe
  outcomes:
    incidCase: #incidence of detected cases
      source:
        incidence:
          infection_stage: "I"
      probability:
        value: 0.5
      delay:
        value: 5
    incidHosp: #incidence of hospitalizations
      source:
        incidence:
          infection_stage: "I"
      probability:
        value: 0.05
      delay:
        value: 7
      duration:
        value: 10
        name: currHosp # will track number of current hospitalizations (ie prevalence)
    incidDeath: #incidence of deaths
      source: incidHosp
      probability:
        value: 0.2
      delay:
        value: 14

outcome_modifiers:
  scenarios:
    - test_limits
  modifiers:
    # assume that due to limitations in testing, initially the case detection probability was lower
    test_limits:
      method: SinglePeriodModifier
      parameter: incidCase
      subpop: "all"
      period_start_date: 2020-02-01
      period_end_date: 2020-06-01
      value: 0.5

