name: flepicommon-ci

on:
  workflow_dispatch:
  push:
    paths:
      - flepimop/R_packages/flepicommon/**/*
    branches:
      - main
      - dev
  pull_request:
    paths:
      - flepimop/R_packages/flepicommon/**/*
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R-version: ["4.3.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup R ${{ matrix.R-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R-version }}
      - name: Build flepicommon
        run: |
          R CMD build flepimop/R_packages/flepicommon/
        shell: bash
      - name: Install Dependencies
        run: |
          files <- list.files()
          pkg <- files[startsWith(files, "flepicommon_")]
          install.packages(pkg, dependencies=TRUE)
          install.packages("testthat")
        shell: Rscript {0}
      - name: Install flepicommon
        run: |
          TAR_GZ=$( find . -maxdepth 1 -regex ".*flepicommon.*" -printf "%P\n" )
          DEST=$( R -s -e "cat(.libPaths()[1L])" | xargs )
          R CMD install $TAR_GZ $DEST
      - name: Run Unit Tests
        run: |
          library(flepicommon)
          library(testthat)
          test_local("flepimop/R_packages/flepicommon")
        shell: Rscript {0}
