name: flepicommon-ci

on:
  workflow_dispatch:
  push:
    paths:
      - flepimop/R_packages/flepicommon/**/*
    branches:
      - main
      - dev
  pull_request:
    paths:
      - flepimop/R_packages/flepicommon/**/*
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R-version: ["4.3.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup R ${{ matrix.R-version }}
        uses: r-lib/actions/setup-r@v2
      - name: Install Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools
          working-directory: 'flepimop/R_packages/flepicommon'
      - name: Run Unit Tests
        run: |
          library(devtools)
          setwd("flepimop/R_packages/flepicommon")
          devtools::test(stop_on_failure=TRUE)
        shell: Rscript {0}
