name: flepicommon-ci

on:
  workflow_dispatch:
  push:
    paths:
      - flepimop/R_packages/flepicommon/**/*
    branches:
      - main
      - dev
  pull_request:
    paths:
      - flepimop/R_packages/flepicommon/**/*
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R-version: ["4.3.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install R
        run: |
          UBUNTU_VERSION=$( echo "$( lsb_release -r )" | awk '{print $2}' | sed 's/\.//g' )
          curl -O https://cdn.rstudio.com/r/ubuntu-${UBUNTU_VERSION}/pkgs/r-${R_VERSION}_1_amd64.deb
          sudo apt-get update
          sudo apt-get install ./r-${R_VERSION}_1_amd64.deb
          ln -s /opt/R/${R_VERSION}/bin/R /usr/local/bin/R
          ln -s /opt/R/${R_VERSION}/bin/Rscript /usr/local/bin/Rscript
          echo "-"
          sudo ls -lah /opt/R/4.3.3/lib/R/library
          echo "-"
        shell: bash
        env:
          R_VERSION: ${{ matrix.R-version }}
      - name: Build flepicommon
        run: |
          R CMD build flepimop/R_packages/flepicommon/
        shell: bash
      - name: Install Dependencies
        run: |
          files <- list.files()
          pkg <- files[startsWith(files, "flepicommon_")]
          install.packages(pkg, dependencies = TRUE)
          install.packages("devtools")
        shell: Rscript {0}
      - name: Install flepicommon
        run: |
          R CMD install --help
          echo "-"
          TAR_GZ=$( find . -maxdepth 1 -regex ".*flepicommon.*" -printf "%P\n" )
          R CMD install $TAR_GZ
      - name: Run Unit Tests
        run: |
          setwd("flepimop/R_packages/flepicommon")
          library(devtools)
          devtools::test(stop_on_failure = TRUE)
        shell: Rscript {0}
