name: inference CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - flepimop/R_packages/inference/**/*
      - flepimop/R_packages/flepicommon/**/*
      - examples/**/*
      - flepimop/gempyor_pkg/**/*
    branches:
      - dev
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        R-version: ["4.3"]
    steps:
      - name: Checkout flepiMoP
        uses: actions/checkout@v4
        with:
          lfs: true
          sparse-checkout: |
            *
            !documentation/
          sparse-checkout-cone-mode: false
          persist-credentials: false
      - name: Install flepiMoP
        uses: ./.github/actions/flepimop-install
        with:
          python-version: ${{ matrix.python-version }}
          R-version: ${{ matrix.R-version }}
      - name: Run tests
        run: |
          conda activate venv/
          export FLEPI_PATH=$(pwd)
          Rscript -e "library(testthat); test_package('inference')"
        shell: bash -el {0}
